# SPDX-License-Identifier: MIT
# Copyright (c) 2020 The Authors.

# Authors: Phu Tran          <@phudtran>

apiVersion: v1
kind: ServiceAccount
metadata:
  name: zeta-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zeta-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: zeta-operator
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeta-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeta-operator
  template:
    metadata:
      labels:
        app: zeta-operator
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      serviceAccountName: zeta-operator
      terminationGracePeriodSeconds: 0
      hostNetwork: true
      containers:
        - image: localhost:5000/zeta_opr:latest
          name: zeta-operator
          securityContext:
            privileged: true
