# SPDX-License-Identifier: MIT
# Copyright (c) 2020 The Authors.

# Authors: Phu Tran          <@phudtran>

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: chains.zeta.com
spec:
  scope: Namespaced
  group: zeta.com
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: Chain
    plural: chains
    singular: chain
    shortNames:
      - chain
      - chains
  validation:
    openAPIV3Schema:
      properties:
        ftns:
          type: array
          items:
            type: string
  additionalPrinterColumns:
    - name: Status
      type: string
      priority: 0
      JSONPath: .spec.status
      description: The Current Status of the Chain
    - name: Dft
      type: string
      priority: 0
      JSONPath: .spec.dft
      description: The Dft this chain belongs to
    - name: Size
      type: integer
      priority: 0
      JSONPath: .spec.size
      description: The size of the chain
    - name: CreateTime
      type: string
      priority: 0
      JSONPath: .spec.createtime
      description: Time the object is created
    - name: ProvisionDelay
      type: string
      priority: 0
      JSONPath: .spec.provisiondelay
      description: Time to provision an object from creation
