# SPDX-License-Identifier: MIT
# Copyright (c) 2020 The Authors.

# Authors: Sherif Abdelwahab <@zasherif>
#          Phu Tran          <@phudtran>
#          Rio Zhu           <@zzxgzgz>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:The above copyright
# notice and this permission notice shall be included in all copies or
# substantial portions of the Software.THE SOFTWARE IS PROVIDED "AS IS",
# WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
# TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
# FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
# THE USE OR OTHER DEALINGS IN THE SOFTWARE.

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: droplets.zeta.com
spec:
  scope: Namespaced
  group: zeta.com
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: Droplet
    plural: droplets
    singular: droplet
    shortNames:
      - drp
      - drps
  additionalPrinterColumns:
    - name: Status
      type: string
      priority: 0
      JSONPath: .spec.status
      description: The Current Status of the droplet
    - name: Interface
      type: string
      priority: 0
      JSONPath: .spec.itf
      description: The main interface of the droplet
    - name: IpControl
      type: string
      priority: 0
      JSONPath: .spec.ip_control
      description: The Node ZGC interface ip
    - name: CreateTime
      type: string
      priority: 0
      JSONPath: .spec.createtime
      description: Time the object is created
    - name: ProvisionDelay
      type: string
      priority: 0
      JSONPath: .spec.provisiondelay
      description: Time to provision an object from creation
    - name: Network
      type: string
      priority: 0
      JSONPath: .spec.network
      description: A droplet's physical connectivity, can be either "tenant" or "zgc"
    - name: Zgc_id
      type: string
      priority: 0
      JSONPath: .spec.zgc_id
      description: ZGC id
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            status:
              type: string
            mac:
              type: array
              items: string
            ip:
              type: array
              items: string
            interface:
              type: string
            createTime:
              type: string
            provisionDelay:
              type: string
            network:
              type: string
            zgc_id:
              type: string
