---
#
# SPDX-License-Identifier: MIT
#
# Copyright (c) 2020 The Authors.
# Authors: Bin Liang  <@liangbin>
#
# Summary: Site specific playbook variables for site named "lab"
#
ansible_port: 22
ansible_user: "ubuntu"
k8s_type: "microk8s"
