---
#
# SPDX-License-Identifier: MIT
#
# Copyright (c) 2020 The Authors.
# Authors: Bin Liang  <@liangbin>
#
# Summary: Play to create k8s cluster on target site
#
## ============== Play to provision site for Zeta deployment ============================
- name: "==== Validate and prepare the site nodes with common features"
  hosts: kube_master:kube_nodes:zgc      # host in either groups
  gather_facts: true
  vars:
    local_user: "{{ansible_user}}"
  tasks:
    - name: "Provision base node features at {{ site }} site"
      block:
        - name: "make sure they have minimum RAM required"
          fail: msg="not enough RAM"
          when: ansible_memory_mb.real.total < 1900
          
        - name: "make sure the system encoding is utf-8"
          become: yes
          template:
            src: templates/locale
            dest: /etc/default/locale
            owner: root
            group: root
            mode: 0644
    
        - include: tasks/apt.yml
        - include: tasks/ubuntu.yml

      when: site != "kind"     # End of non-kind block

- name: "==== Provision K8S cluster on management nodes at {{ site }} site"
  hosts: kube_master:kube_nodes      # host in either groups
  gather_facts: false
  vars:
    local_user: "{{ansible_user}}"
  tasks:
    - name: "Remote Microk8s cluster provisioning task block"
      block:
        - include: tasks/microk8s-all.yml
    
      when: site != "kind"    # End of non-kind block

    - name: "Local KIND cluster provisioning task block"
      block:
        - name: "Setting up Kind cluster"
          shell: "../kind/create_cluster.sh {{stage}} {{k8s_size}} {{droplet_size}} &>> {{DBG_LOG}}"
          args: 
            executable: /bin/bash
          environment:
            STAGE: "{{stage}}"
            REG: "{{reg}}"
          register: "output"
        - debug: var=output.stdout

      when: site == "kind"     # End of kind block

- name: "==== Provision K8S master nodes at {{ site }} site"
  hosts: kube_master
  vars:
    local_user: "{{ansible_user}}"
  tasks:
    - include: tasks/microk8s-master.yml
      when: site != "kind"   
