---
#
# SPDX-License-Identifier: MIT
#
# Copyright (c) 2020 The Authors.
# Authors: Bin Liang  <@liangbin>
#
# Summary: Tasks to install basic tools on microk8s cluster nodes
#
- name: update apt
  apt: update_cache=yes
  become: yes

- name: install base packages
  apt: pkg={{ item }} state=latest
  become: yes
  with_items:
    - git-core
    - curl
    - zlib1g-dev
    - build-essential
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - vim
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - nfs-common
    - python3
    - python3-pip
    - ethtool
    - libffi-dev
    - python3-dev
    - htop
    - zip
    - snapd
    - rpcbind
