---
#
# SPDX-License-Identifier: MIT
#
# Copyright (c) 2020 The Authors.
# Authors: Bin Liang  <@liangbin>
#
# Summary: Tasks for ZGC nodes provisioning
#
# ----------------------------------------------------
# Provision ZGC node  
# ----------------------------------------------------

- name: Get running transitd processes
  become: yes
  shell: "ps -ef | grep -v grep | grep -w transitd | awk '{print $2}'"
  register: running_processes

- name: Kill running transitd processes
  become: yes
  shell: "kill {{ item }}"
  with_items: "{{ running_processes.stdout_lines }}"

- wait_for:
    path: "/proc/{{ item }}/status"
    state: absent
  with_items: "{{ running_processes.stdout_lines }}"
  become: yes
  ignore_errors: yes
  register: killed_processes

- name: Force kill stuck transitd processes
  become: yes
  shell: "kill -9 {{ item }}"
  with_items: "{{ killed_processes.results | select('failed') | map(attribute='item') | list }}"

- name: Remove existing deployment
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /trn_bin
    - /trn_xdp

- name: update apt
  apt: update_cache=yes
  become: yes

- name: install additional packages
  apt: pkg={{ item }} state=latest
  become: yes
  with_items:
    - gdb
    - rpcbind

- name: "Copy ZGC tools to /trn_bin"
  become: yes
  copy:
      src: ../../tools/
      dest: /trn_bin/
      mode: '0755'
      force: yes

- name: "Copy ZGC node executables to /trn_bin"
  become: yes
  copy:
      src: ../../build/bin/
      dest: /trn_bin/
      mode: '0755'
      force: yes

- name: "Copy ZGC node pbf objects to /trn_xdp"
  become: yes
  copy:
      src: ../../build/xdp/
      dest: /trn_xdp/
      force: yes

- name: "Symbol link pbf filesystem"
  become: yes
  shell: rm -rf /bpffs && ln -s /sys/fs/bpf /bpffs
  args: 
    executable: /bin/bash

- name: "Update kernel to 5.6.0-rc2 if needed"
  become: yes
  shell: "printf 'y\nn\n' | sudo /trn_bin/kernelupdate.sh"

- name: Reboot host and wait for it to restart
  become: yes
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami

# ----------------------------------------------------
# Bootstrap ZGC Node
# ----------------------------------------------------
- name: "Kick start ZGC Daemon"
  become: yes
  shell: |
    /etc/init.d/rpcbind restart
    /etc/init.d/rsyslog restart
    ip link set eth2 promisc on
    ip link set dev eth1 up mtu 9000
    ip link set dev eth2 up mtu 9000
    nohup /trn_bin/transitd >/tmp/transitd.std 2>&1 &
  args: 
    executable: /bin/bash
